server: 
   port: 0   
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
   servlet:
      contextPath: /airports   
spring:
  thymeleaf: ## Thymeleaf Config
      cache: false  
  main.allow-bean-definition-overriding: true
  application.name: airportsdata
  boot.admin: #Spring Boot Admin Config    
      client.url: http://localhost:18100/monitoring
      client.username: operations
      client.password: changeIt2019!
      client.service-url: http://localhost:0/airports

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always  

onesaitplatform:
  iotclient:
    multitenant: false
    urlRestIoTBroker: https://development.onesaitplatform.com/iot-broker
    sslverify: false
    token: 1bae7725becf47a7a17b3ec203eb652a
    deviceTemplate: airportsdataDeviceMicroservice
    device: airportsdata
    connectTimeoutInSec: 10
    writeTimeoutInSec: 30
    readTimeoutInSec: 30


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: onesaitplatform
      clientSecret: onesaitplatform
      accessTokenUri: https://development.onesaitplatform.com/oauth-server/oauth/token
      userAuthorizationUri: https://development.onesaitplatform.com/oauth-server/oauth/authorize
      checkTokenEndpointUrl: https://development.onesaitplatform.com/oauth-server/oauth/check_token
      useCurrentUri: true
    resource:
      userInfoUri: https://development.onesaitplatform.com/oauth-server/user


    ## LOGGING CONF
logging:
   path: /tmp/logs 
   file: airportsdata
   level:
      com.minsait: DEBUG 
      #org.springframework.security: DEBUG

